default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yushiro
  password:

development:
  <<: *default
  database: stmn-study-4th_development

test:
  <<: *default
  database: stmn-study-4th_test

production:
  <<: *default
  database: stmn-study-4th_production
  username: stmn-study-4th
  password: <%= ENV['STMN-STUDY-4TH_DATABASE_PASSWORD'] %>
